version: 2.1

jobs:
  linux_build:
    machine: 
      image: ubuntu-1604:201903-01 # the primary container, where your job's commands are run
    resource_class: medium
    steps:
      - checkout
      - run: docker --version
      - run: docker pull jonmmease/kaleido-builder:0.6
      - run: docker run -it -v `pwd`/repos/:/repos  jonmmease/kaleido-builder:0.6 /repos/linux_full_scripts/build_kaleido
      - run: sudo chmod -R 777 repos/build
      - run: sudo chmod -R 777 repos/kaleido/py
      - run: ls repos/build/kaleido
      - run: pushd repos/build && zip -r kaleido_linux.zip ./*
      - run: pushd repos/kaleido/py/ && zip -r kaleido_wheel.zip ./dist
      - store_artifacts:
          path: ./repos/build/kaleido_linux.zip
      - store_artifacts:
          path: ./repos/kaleido/py/kaleido_wheel.zip

  mac_build:
    macos:  # indicate that we are using the macOS executor
      xcode: 11.3.0 # indicate our selected version of Xcode
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Delete Simulators to save space
          command: sudo rm -rf /Library/Developer/CoreSimulator/Profiles/Runtimes/
      - run:
          command: ./repos/mac_scripts/fetch_chromium
          no_output_timeout: 30m
      - run:
          command: ./repos/mac_scripts/build_kaleido
          no_output_timeout: 30m
      - run: ls repos/build/kaleido_mac
      - run: pushd repos/build && zip -r kaleido_mac.zip ./*
      - store_artifacts:
          path: ./repos/build/kaleido_mac.zip

workflows:
  build-all:
    jobs:
      #- mac_build
      - linux_build
