version: 2.1
jobs:
  build:
    machine: 
      image: ubuntu-1604:201903-01 # the primary container, where your job's commands are run
    resource_class: medium
    steps:
        - checkout
        - run: docker --version
